### ISSUE TITLE
Request for Access to Code in Your Paper

### ISSUE THREAD

**Issue by wl1282215100** [TapasKumarDutta1/ARM-Net#1]
Dear Tapas Kumar Dutta,

I hope this message finds you well. I wanted to express my sincere interest in your recent paper. Your research has garnered significant attention in my field, and I believe that access to your code would be a valuable resource for me.

In your paper, I have come across some fascinating methods and techniques that I would like to delve into and explore further. If possible, would it be feasible for me to obtain access to your code for the purpose of in-depth study and experimentation?

I completely understand that sharing code may involve some complexities, and I assure you that I will use it with care and respect any relevant licenses or agreements. If you require any additional information or have specific requirements for sharing the code, I am more than willing to comply.

Once again, thank you for your contributions to the research community, and I look forward to your response.

Warm regards

**Comment by TapasKumarDutta1** [comment]
Thank you for your kind words and your interest in my recent paper. I am delighted to hear that you find the methods and techniques outlined in the research intriguing, and I appreciate your desire to delve into them further.

I sincerely apologize for the delay in providing access to the code. Your enthusiasm for my work is truly motivating, and I understand the importance of timely access to such resources.

I want to assure you that I am committed to sharing the code with you as soon as possible. Unfortunately, due to unforeseen circumstances, I have experienced a delay in preparing the code for distribution. Please accept my apologies for any inconvenience this may have caused.

I understand the significance of your request and will prioritize the completion of this task. I aim to upload the code at the earliest opportunity. I appreciate your patience and understanding in this matter.

If there are any specific requirements or additional information you need during this process, please feel free to let me know. I value your commitment to using the code responsibly and respecting any relevant licenses or agreements.

Once again, thank you for your interest and understanding. I look forward to providing you with access to the code shortly.

Warm regards,

Tapas Kumar Dutta
